### ISSUE TITLE
HDR data in test_withoutGT folder

### ISSUE THREAD

**Issue by ZPM526** [shuaizhengliu/Joint-HDRDN#5]
The npz file loaded from test_withoutGT folder also has HDR field attached to it. But according to the description given by the author, there should be no GT HDR for data within this folder so I guess it is a "fake HDR" which has no meaning?

**Comment by shuaizhengliu** [comment]
yes, the "HDR" part of data in test_withoutGT has no meaning. Initially, I set it for facilitating reuse of test code for test data with GT.
